language: node_js
node_js:
- '0.10'
before_script:
- npm install -g gulp
deploy:
  provider: s3
  access_key_id: AKIAJMGDAX6442OAY7FA
  secret_access_key:
    secure: Ov586iScE3MwQ6jRs6/wB4/skSKKMK+YW6X+o87kNXfou1XgVSav6Iu/9plDLnhbXz63gMJDflZYwgYfDWsJglB2V5iGzdtjFDqKnnL7xwhoT0hv4bEhKx4CCrbxLR/QCcRMFB5rALVNl73esInHp96cfFLZdR/FKybJSJvwAvA=
  bucket: goangular-travis-test
  local-dir: build
  upload-dir: build
  on:
    tags: true
    repo: colinmacdonald/goangular
    branch: master
