language: node_js
node_js:
- '0.10'
before_script:
- npm install -g gulp
deploy:
  provider: s3
  bucket: "S3 Bucket"
  skip_cleanup: true
  local-dir: build
  upload-dir: travis-builds
  on:
    tags: true
    branch: master
