language: node_js
node_js:
- '0.10'
before_script:
- npm install -g gulp
- echo "$TRAVIS_COMMIT"
- echo "$TRAVIS_BRANCH"
- echo "test/ $TRAVIS_BUILD_NUMBER /testtest"
- ./script.sh
after_success:
- echo "pass"
before_deploy:
- gulp build
deploy:
  provider: s3
  access_key_id: "$AWS_S3_ID"
  secret_access_key: "$AWS_S3_SECRET"
  bucket: goangular-travis-test
  local-dir: dist
  upload-dir: "integrations/goangular/$TRAVIS_BRANCH"
  on:
    tags: true
    all_branches: true
    repo: colinmacdonald/goangular
after_deploy:
- echo "deployed"
env:
  global:
  - secure: UGEqnlRb4EjhaNbsHtzLmSV5lXxj82b2VcfokM7RlFH1NBTm8aREBuDwyPjo7dSDsGYHf1Ehy//VLa+1JLsJtWb1wpf6oNEjYvszjfTw2AAAej4tS/HAdldRWEBZWuW5epq+M5/U+vm4ETZwYBgNmyxnmwVnPfYUOfrt/Y3Mu9I=
  - secure: DWVkqwYdmtwuFKAv7GmJbnEjM6R0Zgfx9By3Jk4ULRrae86KWyxSbIgs+/+NHqP+0E3Cb+vKQjiJicEQ6Q8U70+9ocJuW28DOZhcAXgb0OFJrzuWKngJUVdsGkr8EKDK3en34csAxmfhCFuwxb110+r5NBki5FMAvN+rSXjurjI=
