language: node_js
node_js:
- '0.10'
before_script:
- npm install -g gulp
- source deploy/tags.sh
before_deploy:
- gulp build
deploy:
- provider: s3
  access_key_id: "$AWS_S3_ID"
  secret_access_key: "$AWS_S3_SECRET"
  bucket: goangular-travis-test
  local-dir: dist
  upload-dir: "integrations/goangular/latest/$TRAVIS_BRANCH"
  on:
    repo: colinmacdonald/goangular
    condition:
    - $IS_TAG = true
    - $IS_LATEST = true
- provider: s3
  access_key_id: "$AWS_S3_ID"
  secret_access_key: "$AWS_S3_SECRET"
  bucket: goangular-travis-test
  local-dir: dist
  upload-dir: "integrations/goangular/$TRAVIS_BRANCH"
  on:
    repo: colinmacdonald/goangular
    condition:
    - $IS_TAG = true
after_deploy:
- echo "deployed $TRAVIS_BRANCH"
env:
  global:
  - secure: UGEqnlRb4EjhaNbsHtzLmSV5lXxj82b2VcfokM7RlFH1NBTm8aREBuDwyPjo7dSDsGYHf1Ehy//VLa+1JLsJtWb1wpf6oNEjYvszjfTw2AAAej4tS/HAdldRWEBZWuW5epq+M5/U+vm4ETZwYBgNmyxnmwVnPfYUOfrt/Y3Mu9I=
  - secure: DWVkqwYdmtwuFKAv7GmJbnEjM6R0Zgfx9By3Jk4ULRrae86KWyxSbIgs+/+NHqP+0E3Cb+vKQjiJicEQ6Q8U70+9ocJuW28DOZhcAXgb0OFJrzuWKngJUVdsGkr8EKDK3en34csAxmfhCFuwxb110+r5NBki5FMAvN+rSXjurjI=
