language: node_js
node_js:
- '0.10'
before_script:
- npm install -g gulp
- source deploy/tags.sh
before_deploy:
- gulp build
deploy:
- provider: s3
  access_key_id: $AWS_S3_ID
  secret_access_key: $AWS_S3_SECRET
  bucket: goangular-travis-test
  local-dir: dist
  upload-dir: integrations/goangular/latest
  on:
    all_branches: true
    repo: goinstant/goangular
    condition:
    - $IS_TAG != 0
    - $IS_LATEST != 0
- provider: s3
  access_key_id: $AWS_S3_ID
  secret_access_key: $AWS_S3_SECRET
  bucket: goangular-travis-test
  local-dir: dist
  upload-dir: integrations/goangular/$TRAVIS_BRANCH
  on:
    all_branches: true
    repo: goinstant/goangular
    condition:
    - $IS_TAG != 0
after_deploy:
- echo "deployed $TRAVIS_BRANCH"
notifications:
  hipchat:
    rooms:
    - $HIPCHAT_ROOM1
    - $HIPCHAT_ROOM2
  template:
  - '<a href="%{build_url}">%{branch}</a> - <a href="%{compare_url}">%{commit}</a>
    : %{message}'
  format: html
env:
  global:
  - secure: hofOxLRcWVq2vqH3ZY57pr1JSK3HmosuDsPbfn/Q9smENSfa1wGXypim8uCvbhofXQRfVSLPQNcPBXqvq5fFjn+quPhaMswDupgQkJhwtCpkgTtHCAN2wyrmv8hF31ugT3UdktpikJAgr1y27+IBpa5HYQi5ey7y3ycW8WH4J64=
  - secure: DqlM4haZO7VDHB49aiS4eKWwZ/shrCsHvTDTyP5c5qVWyXXGY9yM0nwIav5M6aWH1qqXQ0BY+QfOjwFck9gob1WqEA7twufOa+Xf+I1MOAUsOuxBZ79DOkSB+RjFJJjSXbIJAv0k4VVHHtKvy3VnGfTc6GrOviqH2ac+rdL+iKo=
  - secure: Kc2aM/N+4ZRJ0OuwmBM5PPlaZYQbWi+ZglqE8jDhFANPtFLMy8ooAXWsyNKt9Feobze5l8kkuUxLowh5DB7UXGPjTPOVf+5srIx0sCqu0Jz1w9CRqUo1xxzswO//bFxHwKACjEJYzBqLOGKrNtrBFvUF70JU7/9Iq9JzZSUvDkg=
  - secure: iVwzuaF8d6D3pu59bPeGskFbDLZU9RrVWRI0bm9CosPaKFcB/97CXIxpENgPnumNWWOVg3jB2gdq0ErqtWSrC5h6L9WnUnt4a31kaXEb14Ahy3p6ozwsA2dYur48IWEIkSviKQRAgALEi7RFv5Wmf/sHkyKOHuT1UVy4QpaOlyI=
